matrix:

- name: markdown documentation
  aspell:
    lang: en
    d: en_US
  sources:
    - docs/source/**/*.md
    - docs/source/**/*.rst
  dictionary:
    wordlists:
      - docs/dictionary/project_wordlist.txt
      - docs/dictionary/sphinx_wordlist.txt
      - docs/dictionary/multiversx_wordlist.txt
      - docs/dictionary/custom_wordlist.txt
    output: build/dictionary/python.dic
  pipeline:
    - pyspelling.filters.markdown:
        markdown_extensions:
          - markdown.extensions.extra
    - pyspelling.filters.html:
        comments: false
        attributes:
        - title
        - alt
        ignores:
        - code
        - pre
        - div#ValuesExamplesTable
