# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    # Install uv and update PATH to the correct location
    - curl -LsSf https://astral.sh/uv/install.sh | sh && export PATH="$HOME/.local/bin:$PATH"
    # Verify uv is installed
    - $HOME/.local/bin/uv --version
    # Create virtual env
    - $HOME/.local/bin/uv venv
    # Activate it with the dot operator
    - . .venv/bin/activate
    # Sync dependencies
    - $HOME/.local/bin/uv sync --group dev
    # add sphinx build
    - sphinx-build -b html docs/source docs/build

sphinx:
   configuration: docs/source/conf.py

