// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            0
// Async Callback (empty):               1
// Total number of exported functions:   2

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    piggy_bank
    (
    )
}

elrond_wasm_node::wasm_empty_callback! {}
