// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   6

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    esdt_minter
    (
        esdtIdentifier
        airdropAmount
        issueToken
        addAirdropAmount
    )
}

elrond_wasm_node::wasm_empty_callback! {}
