[package]
name = "esdt-minter-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Etienne Wallet",]

[dev-dependencies]

[dependencies.esdt-minter]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.38.0"
