// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    trader_sc
    (
        init => init
        upgrade => upgrade
        getJexIdentifier => jex_identifier
        getWegldIdentifier => wegld_identifier
        getJexPairAddress => jex_pair_address
        getExecutorAddress => executor_address
        deposit => deposit
        executeTrade => execute_trade
        withdraw => withdraw
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
